
graph LR

  subgraph Generative Model
    Representation["Representation <br/> (latent space)"] --> Generator[<b>Generator</b>]
  end

  Generator--> Discriminator[<b>Discriminator</b>]

  Sample

  Sample[Sample] --> Discriminator

  Discriminator --> ID[Identification as <br/> generated or true]

  ID -.->|Feedback| Discriminator
  ID -.->|Feedback| Generator
